#!/usr/bin/bash

# /////////////////////////////////////////////////////////////////////////////// #
# Application Name	: srtlogs
# Version						: v.1.0.0
# Author 						: endang.ismaya@gmail.com
# Date 							: March 30, 2015
# Location 					: San Francisco, USA
# Comment						:	Create SRT Logs with Cygwin/OSS with first create sitelist
# /////////////////////////////////////////////////////////////////////////////// #

usage ()
{
	cat <<END
Usage:
./srtlogs [filename]
 
 filename : filename or absolute path name tobe proceed.
END
}

## error catch
error ()
{
	echo "Error: $1"
	usage
	exit $2
} >&2

##// checking if no argument (filename)
[[ $# -gt 2 ]] && { echo "Missing arguments" >&2; usage ; exit 1; }

## set filename variable
filename="$1"
srtfile="srtsitelist"

# check if sitelist more than one
if [[ $filename =~ .*,.* ]]; then
rm ${srtfile}
	 IFS="," read -a array <<< "$filename"
	 
   for (( i=0; i < ${#array[@]} ; i++ )); do
   			sitename="${array[i]}"
   			## echo "${sitename}"
   				echo "${sitename}" >> ${srtfile}
   				# eNBName="${eNBName}_${sitename}_"
   done
# echo "${srtfile}" 
filename="${srtfile}"
else
	echo "$1" > ${srtfile}
	filename="${srtfile}"
fi

##// check the existance of the filename
if [[ ! -e $filename ]]; then
	echo "File ${filename} is not exists" >&2
	exit 1
fi

cat -vn ${filename}

# export eNBName="${eNBName}"
# /home/Aldeqeela/programming/SRT-Yupana/Scripts/srtparse/ddsrt

if [[ $2 ]] ; then

		answer="$2"
		
else
# printf "%s :\n" "Please choose the number to be proceed"
read -p "Execute the sitelist (y/n) : " answer
	if [[ $answer != "y" ]]; then
		exit 1
	fi
fi

## /home/dd622f/newSRT/srtparse -f srtsitelist
/home/ei400b/00_Tools/srt_lte/srtparse -f srtsitelist

exit 0

# //////////////////////////////////////////////////////////////////////////////// #
# Revision.History
# v.1.0.0							-> Mar 31, 2015 Beta Version
# //////////////////////////////////////////////////////////////////////////////// #